exclude_paths:
- 'src/site/**/*'

engines:
  duplication:
    enabled: true
    exclude_paths:
    - 'src/test/**/*'
    - 'src/generated/**/*'
    config:
      languages:
      - java
    checks:
      Similar code:
        enabled: true

  fixme:
    enabled: true
    exclude_paths:
    - 'src/test/**/*'
    - 'src/generated/**/*'

  metrics:
    enabled: true
    exclude_paths:
    - 'src/test/**/*'
    - 'src/generated/**/*'

  coverage:
    enabled: true
    exclude_paths:
    - 'src/test/**/*'
    - 'src/generated/**/*'
