exclude_paths:
  - '**/site/**/*'
  - '**/test/**/*'
  - '**/generated/**/*'

engines:
  duplication:
    enabled: true
    config:
      languages:
      - java
    checks:
      Similar code:
        enabled: true

  fixme:
    enabled: true

  metrics:
    enabled: true

  coverage:
    enabled: true
